### PR TITLE
Reset QA account and other QA changes

### PR DESCRIPTION
**Pull request by emil2k**
- Optionally, allow one to reset the QA account with the `NUKE_QA` environment variable.
- Remove the now unnecessary Go install.
- Add some timeouts.
- Set explicit conditions on jobs/steps to better handle skips and cancellations.
- Combine some jobs and deploy stages for efficiency.
- Reorganize into stages

### CODE REVIEW

**Comment by rifisdfds** [comment]
@emil2k can we do a couple of runs of this? Without the nuke option and then with it to test, or is there a reason not to at this point?

**Comment by emil2k** [comment]
@rifisdfds I tested it with the `NUKE_QA=true` here: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=531715&view=results

And I can queue up another one without that set now.

**Comment by emil2k** [comment]
Made some adjustments to the conditions since skipping of the nuke step affected the subsequent jobs, and queued up some runs:

- With nuke: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=532849&view=results
- Without nuke: https://dev.azure.com/dfds/CloudEngineering/_build/results?buildId=532850&view=results

**Review by avnes — APPROVED** [review]

**Comment by emil2k** [comment]
@avnes I had to make a few more adjustments on this, but this should be ready for review again.

**Review by avnes — APPROVED** [review]

**Pull request merged**
