### PR TITLE
Migrating EBS CSI driver from Helm chart to EKS add-on

### PR DESCRIPTION
**Pull request by emil2k**
The steps to perform the migration:
https://md.dfds.cloud/s/HD-lYgyRB#Steps-to-switch-from-Helm-release-to-EKS-addon

The steps to then test the enabling the `CSIMigration` and `CSIMigrationAWS`:
https://md.dfds.cloud/s/HD-lYgyRB#Enabling-the-migration-feature-gates

That document also has some random notes.

### CODE REVIEW

**Comment by emil2k** [comment]
Rebased this on top of the HCL updates Richard made to get the QA pipeline running and adjusted them to run a 1.23 control plane and AMI. Will run the QA pipeline a few times to verify functionality.

**Review by rifisdfds — DISMISSED** [review]
I have tested this out in 1.22 and everything goes as expected based on the steps involved (terraform state rm, import etc). Seems like really good work. Everything with a PV works before and after, new deployments using the csi-gp2 created afterwards all work.

I suggest we hold off on merging this PR until the point we need it as to not prevent others from releasing to production, and schedule a date/time to perform the upgrade

**Comment by emil2k** [comment]
Sounds good, we can schedule something.

**Comment by emil2k** [comment]
@rifisdfds I wrote up a draft of the maintenance announcement, feel free to edit it here:
https://md.dfds.cloud/s/5Ua1s3y9w

**Pull request merged**
