### PR TITLE
Removed obsolete ecr-repo, because it is unused

### PR DESCRIPTION
**Pull request by wcarlsen**
We do not use this in the ECRRepo. So no need for it I guess.

### CODE REVIEW

**Comment by runeabrahamsson** [comment]
I agree we don't use the module for ECR and it is adding unnecessary maintenance for our code. Let's remove it

**Comment by abstrask** [comment]
This was used to show teams a way to handle their ECR repos themselves, rather than being dependent on us creating them.

I thought it was also used for deploying Harald. At least that's what we agreed, as far as I remember.

**Comment by wcarlsen** [comment]
Harald was suppose to use it, but we ran into issues I think. So Harald is only doing a postgres with Terraform https://github.com/dfds/harald/tree/master/infrastructure.

**Comment by wcarlsen** [comment]
We can always reintroduce if we want to.

**Comment by abstrask** [comment]
See link - it is provisioning its own ECR repo.

**Pull request merged**
