### PR TITLE
Restrict grafana dashboard sidecar namespace selector to monitoring

### PR DESCRIPTION
**Pull request by SEQUOIIA**

### CODE REVIEW

**Review by silviucalin — APPROVED** [review]

**Review by emil2k — APPROVED** [review]
Isn't the sidecar running in the monitoring namespace already? 

>     # Otherwise the namespace in which the sidecar is running will be used.
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L928

I guess this is worth a try still.

**Comment by SEQUOIIA** [comment]
> Isn't the sidecar running in the monitoring namespace already?
> 
> > ```
> > # Otherwise the namespace in which the sidecar is running will be used.
> > ```
> 
> https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L928
> 
> I guess this is worth a try still.

It's not where the sidecar is deployed, but rather where it looks for configmaps.

**Comment by emil2k** [comment]
Yes, I just mean it says that if that setting is unset (as it was) it should default the search to the namespace where it is running.

**Comment by SEQUOIIA** [comment]
Ah, yeah. That is indeed what is written, but the behaviour seen when deployed is different 😬

**Pull request merged**
