### PR TITLE
Allow WAF features in capability accounts

### PR DESCRIPTION
**Pull request by samidbb**

### CODE REVIEW

**Review by rifisdfds — CHANGES_REQUESTED** [review]
I think close this as it actually does the opposite of what we want?

**Comment by wcarlsen** [comment]
@samidbb and @rifisdfds can we have a talk about this?

**Review by jdsmithit — APPROVED** [review]

**Comment by rifisdfds** [comment]
@samidbb Do you want to close this one?

**Comment by rifisdfds** [comment]
Not required

**Pull request closed without merging**
