### PR TITLE
Remove creation of deploy user credentials to move responsibility to the team

### PR DESCRIPTION
**Pull request by jdsmithit**
Update IAM user module to allow for secret creds not to be automatically created when a IAM user is created,

### CODE REVIEW

**Review by samidbb — COMMENTED** [review]
(repeated from comment section) I think also that should be split into 2 PRs as pointed out in the issue to minimise the potential of being blocked.

**Comment by jdsmithit** [comment]
@rifisdfds, @samidbb 1 out of 2 ready for review 👯

**Comment by jdsmithit** [comment]
@samidbb spoke to fish and decided to move back to 1 pr as it's all tied in.

**Review by samidbb — CHANGES_REQUESTED** [review]
When I run the PR first time with create_aws_iam_access_key = false it removed the key and the entry from parameter store. 
But when I tried to re-run with create_aws_iam_access_key = true, then I get this error:

│ Error: error creating SSM Parameter (/managed/deploy/aws-creds): AccessDeniedException: User: arn:aws:sts::454234050858:assumed-role/Prime/aws-go-sdk-1665391981992294717 is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:eu-central-1:454234050858:parameter/managed/deploy/aws-creds because no identity-based policy allows the ssm:PutParameter action
│       status code: 400, request id: 9dd87ebe-2c26-4d88-94a2-7687abbb0711
│ 
│   with module.iam_user_deploy_store_credentials[0].aws_ssm_parameter.putSecureString[0],
│   on ../../_sub/security/ssm-parameter-store/main.tf line 1, in resource "aws_ssm_parameter" "putSecureString":
│    1: resource "aws_ssm_parameter" "putSecureString" {
│ 
╵
ERRO[0022] 1 error occurred:
        * exit status 1

**Comment by rifisdfds** [comment]
I have set the default for creation of iam key to false here, as we will want it to be false after running the script to orphan current keys and ensure no extra keys are regenerated

**Review by samidbb — APPROVED** [review]

**Review by rifisdfds — APPROVED** [review]

**Review by rifisdfds — APPROVED** [review]

**Pull request merged**
